### ISSUE TITLE
Fail to run with noexec /tmp

### ISSUE THREAD

**Issue by breznak** [Aluxian/Whatsie#136]
* Operating system:
Linux, Ubuntu 14.04 LTS, 64bit
* Whatsie version:
`Setting up whatsie (2.0.14-353)`
* Crash: 
```
[Fri, 29 Apr 2016 23:19:35 GMT] /scripts/browser/main.js: [Error: /tmp/.org.chromium.Chromium.VDwXN8: failed to map segment from shared object: Operation not permitted]
ELECTRON_ASAR.js:158
        return old.apply(this, arguments)
                   ^

Error: /tmp/.org.chromium.Chromium.VDwXN8: failed to map segment from shared object: Operation not permitted
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:440:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/opt/whatsie/resources/app.asar/node_modules/spellchecker/lib/spellchecker.js:2:16)
    at Module._compile (module.js:413:34)
```
* Steps to reproduce: 

`/tmp` mounted with `noexec`. It is quite important security measure, can you work around it somehow? 
Thank you,

**Comment by Aluxian** [comment]
Probably not, but I'll see what can be done.

**Comment by michelinux8** [comment]
same for me

**Comment by Aluxian** [comment]
I don't think it's possible to do anything about this issue since Chromium (my app uses Chromium under the hood) needs that kind of access in tmp (my assumption, judging from the log). 

Not all hope is lost, though. If this change is made in Electron (the framework I use), I'll definitely update Whatsie.
