### ISSUE TITLE
Errors doing 'npm install'  on OSX 10.11

### ISSUE THREAD

**Issue by TimNZ** [Aluxian/Whatsie#148]
Jump to the end of the attached log.

[npm-debug.log.zip](https://github.com/Aluxian/Whatsie/files/249861/npm-debug.log.zip)

**Comment by TimNZ** [comment]
Changed "gulp-github-release" => "*" from "1.1.2" which allowed npm install to complete

Now getting error when doing "gulp rebuild:64"
```
[14:42:19] Requiring external module coffee-script/register
module.js:341
    throw err;
    ^

Error: Cannot find module 'publish-release-2'
  at Function.Module._resolveFilename (module.js:339:15)
  at Function.Module._load (module.js:290:25)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at Object.<anonymous> (/Users/timshnaider/Desktop/Development/electron/XeroDesktop/node_modules/gulp-github-release/index.js:1:84)
  at Module._compile (module.js:413:34)
  at Object.Module._extensions..js (module.js:422:10)
  at Module.load (/Users/timshnaider/Desktop/Development/electron/XeroDesktop/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at Object.<anonymous> (/Users/timshnaider/Desktop/Development/electron/XeroDesktop/tasks/publish.coffee:6:17)
  at Object.<anonymous> (/Users/timshnaider/Desktop/Development/electron/XeroDesktop/tasks/publish.coffee:1:1)
  at Module._compile (module.js:413:34)
  at Object.loadFile (/Users/timshnaider/Desktop/Development/electron/XeroDesktop/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/timshnaider/Desktop/Development/electron/XeroDesktop/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at requireDir (/Users/timshnaider/Desktop/Development/electron/XeroDesktop/node_modules/require-dir/index.js:116:33)
  at Object.<anonymous> (/Users/timshnaider/Desktop/Development/electron/XeroDesktop/gulpfile.coffee:5:1)
  at Object.<anonymous> (/Users/timshnaider/Desktop/Development/electron/XeroDesktop/gulpfile.coffee:1:1)
  at Module._compile (module.js:413:34)
  at Object.loadFile (/Users/timshnaider/Desktop/Development/electron/XeroDesktop/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/timshnaider/Desktop/Development/electron/XeroDesktop/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
  at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:193:16)
  at module.exports (/usr/local/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:17:3)
  at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:185:9)
  at /usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:159:9
  at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:108:14
  at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:36:12
  at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:47:7
  at nextTickCallbackWith0Args (node.js:452:9)
  at process._tickCallback (node.js:381:13)
  at Function.Module.runMain (module.js:449:11)
  at startup (node.js:139:18)
  at node.js:999:3
```

**Comment by TimNZ** [comment]
Changed offending require("publish-release-2") in gulp-github-release/index.js to "publish-release"

Got error doing gulp build:darwin64

Once I set GITHUB_OAUTH_TOKEN the build completed.

Great work, tidy up the build process and perhaps update the README.md section on Build to include "GITHUB_TOKEN (optional, in case you get errors from GitHub)" and it's all sweet.

**Comment by Aluxian** [comment]
Thanks! I'm sorry for the error, `publish-release` was unmaintained so I republished it, but then I was assigned as its maintainer so I deprecated the new package. I missed that `require`.

I updated the README, I'll update `gulp-github-release` and that's all I have to do I think.
