### ISSUE TITLE
Cannot read property 'guest' of undefined

### ISSUE THREAD

**Issue by manuel-delverme** [Aluxian/Whatsie#211]
* Operating system:
Ubuntu 15.04

* Whatsie version:
2.0.14-beta

1) load Whatsie
2) click Ctrl+r repetitively

```
TypeError: Cannot read property 'guest' of undefined
    at attachGuest (/opt/whatsie/resources/electron.asar/browser/guest-view-manager.js:163:42)
    at EventEmitter.<anonymous> (/opt/whatsie/resources/electron.asar/browser/guest-view-manager.js:212:10)
    at emitMany (events.js:121:13)
    at EventEmitter.emit (events.js:195:7)
    at EventEmitter.<anonymous> (/opt/whatsie/resources/electron.asar/browser/api/web-contents.js:128:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

**Comment by Aluxian** [comment]
Thanks! I'll look into it.

**Comment by Aluxian** [comment]
Reported upstream: https://github.com/electron/electron/issues/6398

**Comment by Aluxian** [comment]
@manuel-delverme Can you please test 2.0.18 and see if it still happens?

Check for update inside the app or download Whatsie again from https://github.com/Aluxian/Whatsie/releases/tag/v2.0.18
