### ISSUE TITLE
whatsie 2.0.14-353 incompatible with debian stable 7.11 (glibc issue)

### ISSUE THREAD

**Issue by eadixian** [Aluxian/Whatsie#265]
* My Operating system: Debian GNU/Linux 7.11 (wheezy stable)
* Whatsie version: 2.0.14-353
* My GLIBC version: 2.13

Hello.

FYI, in case you're not already aware of this, Whatsie 2.0.14-353 (just apt-get installed today, 17 June 2016) is incompatible with Debian Linux 7.11 stable. The reason: Whatsie 2.0.14-353 appears to require GLIBC 2.14, whereas Debian Linux 7.11 stable only has GLIBC 2.13.

Whatsie error output from command line:

----------------CUT HERE----------------
% whatsie
JavaScript error in the main process
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/.org.chromium.Chromium.jJAo27)
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:440:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/opt/whatsie/resources/app.asar/node_modules/spellchecker/lib/spellchecker.js:2:16)
    at Module._compile (module.js:413:34)
[Fri, 17 Jun 2016 18:20:18 GMT] /scripts/browser/main.js: [Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/.org.chromium.Chromium.jJAo27)]
ELECTRON_ASAR.js:158
        return old.apply(this, arguments)
                   ^

Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/.org.chromium.Chromium.jJAo27)
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:440:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/opt/whatsie/resources/app.asar/node_modules/spellchecker/lib/spellchecker.js:2:16)
    at Module._compile (module.js:413:34)
% file /lib/x86_64-linux-gnu/libc.so.6 
/lib/x86_64-linux-gnu/libc.so.6: symbolic link to `libc-2.13.so'
% 
----------------CUT HERE----------------

Regards,
Eric
--
Eric De Mund
email: ead-whatsie@ixian.com

**Comment by Aluxian** [comment]
Unfortunately, Whatsie cannot run without GLIBC 2.14 and the only way to make it work is to upgrade. Maybe this will help: https://github.com/atom/atom/issues/2020.

I did not know, thanks! I'll update the README to make it clear it's for Debian 8+ only.
