### ISSUE TITLE
whatsie under Fedora 24 won't connect

### ISSUE THREAD

**Issue by Sterntrix** [Aluxian/Whatsie#387]
* Operating system: Fedora release 24  4.6.4-301.fc24.x86_64
* Whatsie version:  whatsie.x86_64    2.0.19-635
I'm getting the following when starting whatsie:
$ whatsie 
ERROR [2016-08-08 19:22:50.040]   whatsie:browser/managers/auto-update-manager: Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1055:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:580:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:412:38)

**Comment by Aluxian** [comment]
Does Chrome work for you?
